services:
  organisation-web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: organisation-web
    restart: unless-stopped
    ports:
      - "8086:80"
    networks:
      - organisation-network

networks:
  organisation-network:
    driver: bridge
