# Generated by Django 5.2.12 on 2026-03-16 18:20

import django.db.models.deletion
import licenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=licenses.models.generate_license_key, max_length=19, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expirée'), ('revoked', 'Révoquée'), ('trial', "Période d'essai")], default='trial', max_length=20)),
                ('trial_period', models.CharField(choices=[('1h', '1 heure'), ('1d', '1 jour'), ('1w', '1 semaine')], default='1d', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_validated', models.DateTimeField(auto_now=True)),
                ('max_activations', models.IntegerField(default=1)),
                ('activation_count', models.IntegerField(default=0)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Licence',
                'verbose_name_plural': 'Licences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('moov', 'Moov Gabon'), ('airtel', 'Airtel Gabon')], max_length=20, unique=True)),
                ('payment_url', models.URLField(max_length=500)),
                ('product_id', models.CharField(max_length=100)),
                ('operation_account_code', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration de paiement',
                'verbose_name_plural': 'Configurations de paiement',
            },
        ),
        migrations.CreateModel(
            name='LicenseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('generated', 'Licence générée'), ('activated', 'Licence activée'), ('validated', 'Licence validée'), ('expired', 'Licence expirée'), ('revoked', 'Licence révoquée'), ('failed', 'Échec validation')], max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='licenses.license')),
            ],
            options={
                'verbose_name': 'Journal de licence',
                'verbose_name_plural': 'Journaux de licence',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_reference_id', models.CharField(max_length=100, unique=True)),
                ('reference', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fees', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('amount_credited', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=50)),
                ('numero_tel', models.CharField(blank=True, max_length=50)),
                ('operator', models.CharField(max_length=50)),
                ('account_operation_code', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Succès'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('code', models.IntegerField(null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='licenses.license')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-received_at'],
            },
        ),
    ]
